name: gomechanic
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: any
  google_fonts: ^4.0.4
  otp_text_field: ^1.1.3
  animated_splash_screen: ^1.3.0
  flutter_screenutil: ^5.7.0
  get_storage: ^2.1.1
  linear_step_indicator: ^1.0.0+3
  timelines: ^0.1.0
  path_provider: ^2.0.15
  geolocator: ^10.0.1
  geocoding: ^2.0.1
  easy_stepper: any
  dropdown_button2: ^2.1.3
  loader_overlay: ^2.2.0
  intl: ^0.18.1
  fluttertoast: ^8.2.2
  open_street_map_search_and_pick: ^0.1.0
  image_picker: ^1.0.4
  pull_to_refresh: ^2.0.0
  firebase_auth: any
#  flutter_html: ^2.2.1
  firebase_core: any
  animate_do: ^3.0.2
  firebase_messaging: any
  flutter_local_notifications: any
  overlay_support: ^2.1.0
#  app_settings: ^5.1.1
  flutter_spinkit: ^5.2.0
  http: any
  dio: ^5.2.1+1
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.3.0
  location: 5.0.0
  url_launcher: ^6.1.5
  animated_text_kit: ^4.2.2
  animated_switch: ^0.0.2
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  anim_search_bar: ^2.0.3
  searchbar_animation: ^0.0.4
  animated_search_bar: ^2.5.0
  jumping_dot: ^0.0.6
  infinite_scroll_pagination: any
  flutter_smart_dialog: ^4.9.4
  google_sign_in: ^6.1.5
  rounded_loading_button: ^2.1.0
  font_awesome_flutter: any
  image_cropper: any
  permission_handler: ^11.0.1
  photo_view: ^0.14.0
  sign_in_button: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/gif/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #